### ISSUE TITLE
Add tests for Discord cogs

### ISSUE THREAD

**Issue by ntgomes** [ntgomes/PollCord#20]
Includes:

- [x] bot.py
- [x] MakerCommands.py
- [x] RecallCommands.py
- [x] modals.py
- [x] questions.py
- [ ] views.py

**Comment by tylerkcraine** [comment]
I found a library call testcord if that something we'd be interested in looking at.

**Comment by ntgomes** [comment]
> I found a library call testcord if that something we'd be interested in looking at.

Pretty sure you are referring to this: https://github.com/KoalaBotUK/testcord. In that case, yeah this can work. Although it seems a bit limited with how much it can cover. We'll have to see how it goes.

**Comment by ntgomes** [comment]
UPDATE: Couldn't fully utilize Pycord, but added tests for the non-active bot functions. From #59
