### ISSUE TITLE
Create CITATION.cff

### ISSUE THREAD

**Issue by ntgomes** [ntgomes/PollCord#4]
Having a CITATION.cff is important for how other forks and derivations of our work will cite the original authors, and should be compatible with our Zenodo DOI page.

**Comment by guptabhishek785** [comment]
#3 is required

**Comment by ntgomes** [comment]
@guptabhishek785 Please use [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7158367.svg)](https://doi.org/10.5281/zenodo.7158367)

**Comment by ntgomes** [comment]
Closed by #23
