### ISSUE TITLE
Create a cog for creating a poll

### ISSUE THREAD

**Issue by ntgomes** [ntgomes/PollCord#5]
A slash command, `/makepoll`, that accepts the following options:
- Name of the poll
    - Check backend to see if that poll exists
- Creator-only questions vs collaborator (anyone can add a question)
- Timeout
    - Whichever question that the timeout occurred on, it would finalize on that question
    - Zero out any other poll questions that weren’t reached

**Comment by tylerkcraine** [comment]
Decided to limit scope of poll manipulation to the creator of the the poll due to framework limitations.
