### ISSUE TITLE
Create a cog for creating an MCQ question in an active poll

### ISSUE THREAD

**Issue by ntgomes** [ntgomes/PollCord#6]
Will be done as a Discord UI modal that will prompt for:
- Name of question
- Comma-separated options, and the bot can verify the input based on that
    - Hard limit is 25 options (pycord limit)

**Comment by ntgomes** [comment]
The soft limit that we have agreed upon is 5.

**Comment by tylerkcraine** [comment]
This is more handled in the views and their life cycle rather than a separate cog in specific

**Comment by ntgomes** [comment]
Okay, that works.
