### ISSUE TITLE
Create a cog for voting on an existing MCQ question

### ISSUE THREAD

**Issue by ntgomes** [ntgomes/PollCord#7]
From user side:
- Just press the button for what you want to vote
- Make it so that buttons are disabled for users that have already voted

From bot side:
- The bot will make up to 5 buttons (up to soft limit)
    - One for each option (up to soft limit)
        - Clicking on that option will add to a count held internally by the bot
    - Plus one for finalizing the results for the question, which is only visible to the poll creator
        - Finalizing would make the bot use the counts for each option, and then display 1st, 2nd, 3rd, in one message.
        - Finalizing will stop the poll and store its results to the backend (which exists) so that it can display the result and clear out the current counts it was keeping up with

**Comment by tylerkcraine** [comment]
This is more handled in the views and their life cycle rather than a separate cog in specific. Also decided a Select ui component would be more flexible for our mcquesion needs.
