### ISSUE TITLE
Create an endpoint for checking if a given guild ID - poll name combination exists

### ISSUE THREAD

**Issue by ntgomes** [ntgomes/PollCord#8]
GET endpoint → “/check/{guild_id}/{poll_name}”
Returns:
```
{
    “exists”: true/false
}
```

**Comment by AbhimanyuBellam** [comment]
Do most people use endpoint format like this, for get request?
 /check?guild_id=441234&poll_name=test_poll
@ntgomes

**Comment by ntgomes** [comment]
@AbhimanyuBellam Good question. I guess the way we had it previously, with paths instead of query params, it would be often used to indicate resources instead of filters. But both seem to apply here.

I'm not entirely sure how you structured the poll data in the backend/database. If we had multiple tables for polls, questions, results, etc., then keeping it as paths would make sense since it stays in line with the concept of resources.

However, if you chose to have them as columns, then it would make sense to do query params.

Honestly, the way I see it, maybe it should be /check/:guild_id?poll_name=test%20poll (%20 since underscores and spaces are handled differently in URLs). Guild ID should still point to a resource, and poll_name could be the filter. But there's only one of the same poll name per guild ID... so it could also be treated just as much as a resource. So either approach could still work given the convention.

[Link for more info](https://stackoverflow.com/questions/30967822/when-do-i-use-path-params-vs-query-params-in-a-restful-api#31261026)

Let me know if you change it based on what we originally discussed, since that would mean I need to change api.py to account for this.

**Comment by AbhimanyuBellam** [comment]
I agree. Also, the initial “/check/{guild_id}/{poll_name}” also has the same inherent meaning. So we will go ahead with the initial thought.

**Comment by ntgomes** [comment]
Closed with #28
